cc_library(
    name = "resource_util",
    srcs = ["resource_util.cc"],
    hdrs = ["resource_util.h"],
    deps = [
      "@com_google_mediapipe//mediapipe/util:resource_util",
      "//mediapipe_api:common",
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
