cc_library(
    name = "asset_manager",
    srcs = ["asset_manager.cc"],
    hdrs = ["asset_manager.h"],
    deps = [
      "@com_google_mediapipe//mediapipe/framework/port:logging",
      "@com_google_mediapipe//mediapipe/framework/port:ret_check",
      "@com_google_mediapipe//mediapipe/framework/port:status",
      "@com_google_mediapipe//mediapipe/util:asset_manager",
      "//mediapipe_api:common",
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
