// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/tasks/cc/audio/audio_classifier/proto/audio_classifier_graph_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe.Tasks.Audio.AudioClassifier.Proto {

  /// <summary>Holder for reflection information generated from mediapipe/tasks/cc/audio/audio_classifier/proto/audio_classifier_graph_options.proto</summary>
  public static partial class AudioClassifierGraphOptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/tasks/cc/audio/audio_classifier/proto/audio_classifier_graph_options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AudioClassifierGraphOptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClRtZWRpYXBpcGUvdGFza3MvY2MvYXVkaW8vYXVkaW9fY2xhc3NpZmllci9w",
            "cm90by9hdWRpb19jbGFzc2lmaWVyX2dyYXBoX29wdGlvbnMucHJvdG8SLG1l",
            "ZGlhcGlwZS50YXNrcy5hdWRpby5hdWRpb19jbGFzc2lmaWVyLnByb3RvGiRt",
            "ZWRpYXBpcGUvZnJhbWV3b3JrL2NhbGN1bGF0b3IucHJvdG8aLG1lZGlhcGlw",
            "ZS9mcmFtZXdvcmsvY2FsY3VsYXRvcl9vcHRpb25zLnByb3RvGkdtZWRpYXBp",
            "cGUvdGFza3MvY2MvY29tcG9uZW50cy9wcm9jZXNzb3JzL3Byb3RvL2NsYXNz",
            "aWZpZXJfb3B0aW9ucy5wcm90bxowbWVkaWFwaXBlL3Rhc2tzL2NjL2NvcmUv",
            "cHJvdG8vYmFzZV9vcHRpb25zLnByb3RvItsCChtBdWRpb0NsYXNzaWZpZXJH",
            "cmFwaE9wdGlvbnMSPQoMYmFzZV9vcHRpb25zGAEgASgLMicubWVkaWFwaXBl",
            "LnRhc2tzLmNvcmUucHJvdG8uQmFzZU9wdGlvbnMSWgoSY2xhc3NpZmllcl9v",
            "cHRpb25zGAIgASgLMj4ubWVkaWFwaXBlLnRhc2tzLmNvbXBvbmVudHMucHJv",
            "Y2Vzc29ycy5wcm90by5DbGFzc2lmaWVyT3B0aW9ucxInCh9kZWZhdWx0X2lu",
            "cHV0X2F1ZGlvX3NhbXBsZV9yYXRlGAMgASgBMngKA2V4dBIcLm1lZGlhcGlw",
            "ZS5DYWxjdWxhdG9yT3B0aW9ucxiM/rTXASABKAsySS5tZWRpYXBpcGUudGFz",
            "a3MuYXVkaW8uYXVkaW9fY2xhc3NpZmllci5wcm90by5BdWRpb0NsYXNzaWZp",
            "ZXJHcmFwaE9wdGlvbnNCWgo2Y29tLmdvb2dsZS5tZWRpYXBpcGUudGFza3Mu",
            "YXVkaW8uYXVkaW9jbGFzc2lmaWVyLnByb3RvQiBBdWRpb0NsYXNzaWZpZXJH",
            "cmFwaE9wdGlvbnNQcm90bw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, global::Mediapipe.CalculatorOptionsReflection.Descriptor, global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptionsReflection.Descriptor, global::Mediapipe.Tasks.Core.Proto.BaseOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions), global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions.Parser, new[]{ "BaseOptions", "ClassifierOptions", "DefaultInputAudioSampleRate" }, null, null, new pb::Extension[] { global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AudioClassifierGraphOptions : pb::IMessage<AudioClassifierGraphOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioClassifierGraphOptions> _parser = new pb::MessageParser<AudioClassifierGraphOptions>(() => new AudioClassifierGraphOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioClassifierGraphOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClassifierGraphOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClassifierGraphOptions(AudioClassifierGraphOptions other) : this() {
      _hasBits0 = other._hasBits0;
      baseOptions_ = other.baseOptions_ != null ? other.baseOptions_.Clone() : null;
      classifierOptions_ = other.classifierOptions_ != null ? other.classifierOptions_.Clone() : null;
      defaultInputAudioSampleRate_ = other.defaultInputAudioSampleRate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClassifierGraphOptions Clone() {
      return new AudioClassifierGraphOptions(this);
    }

    /// <summary>Field number for the "base_options" field.</summary>
    public const int BaseOptionsFieldNumber = 1;
    private global::Mediapipe.Tasks.Core.Proto.BaseOptions baseOptions_;
    /// <summary>
    /// Base options for configuring MediaPipe Tasks, such as specifying the TfLite
    /// model file with metadata, accelerator options, etc.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.Tasks.Core.Proto.BaseOptions BaseOptions {
      get { return baseOptions_; }
      set {
        baseOptions_ = value;
      }
    }

    /// <summary>Field number for the "classifier_options" field.</summary>
    public const int ClassifierOptionsFieldNumber = 2;
    private global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptions classifierOptions_;
    /// <summary>
    /// Options for configuring the classifier behavior, such as score threshold,
    /// number of results, etc.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptions ClassifierOptions {
      get { return classifierOptions_; }
      set {
        classifierOptions_ = value;
      }
    }

    /// <summary>Field number for the "default_input_audio_sample_rate" field.</summary>
    public const int DefaultInputAudioSampleRateFieldNumber = 3;
    private readonly static double DefaultInputAudioSampleRateDefaultValue = 0D;

    private double defaultInputAudioSampleRate_;
    /// <summary>
    /// The default sample rate of the input audio. Must be set when the
    /// AudioClassifier is configured to process audio stream data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DefaultInputAudioSampleRate {
      get { if ((_hasBits0 & 1) != 0) { return defaultInputAudioSampleRate_; } else { return DefaultInputAudioSampleRateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        defaultInputAudioSampleRate_ = value;
      }
    }
    /// <summary>Gets whether the "default_input_audio_sample_rate" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDefaultInputAudioSampleRate {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "default_input_audio_sample_rate" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDefaultInputAudioSampleRate() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioClassifierGraphOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioClassifierGraphOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseOptions, other.BaseOptions)) return false;
      if (!object.Equals(ClassifierOptions, other.ClassifierOptions)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DefaultInputAudioSampleRate, other.DefaultInputAudioSampleRate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseOptions_ != null) hash ^= BaseOptions.GetHashCode();
      if (classifierOptions_ != null) hash ^= ClassifierOptions.GetHashCode();
      if (HasDefaultInputAudioSampleRate) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DefaultInputAudioSampleRate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseOptions_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseOptions);
      }
      if (classifierOptions_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClassifierOptions);
      }
      if (HasDefaultInputAudioSampleRate) {
        output.WriteRawTag(25);
        output.WriteDouble(DefaultInputAudioSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseOptions_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseOptions);
      }
      if (classifierOptions_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClassifierOptions);
      }
      if (HasDefaultInputAudioSampleRate) {
        output.WriteRawTag(25);
        output.WriteDouble(DefaultInputAudioSampleRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseOptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseOptions);
      }
      if (classifierOptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClassifierOptions);
      }
      if (HasDefaultInputAudioSampleRate) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioClassifierGraphOptions other) {
      if (other == null) {
        return;
      }
      if (other.baseOptions_ != null) {
        if (baseOptions_ == null) {
          BaseOptions = new global::Mediapipe.Tasks.Core.Proto.BaseOptions();
        }
        BaseOptions.MergeFrom(other.BaseOptions);
      }
      if (other.classifierOptions_ != null) {
        if (classifierOptions_ == null) {
          ClassifierOptions = new global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptions();
        }
        ClassifierOptions.MergeFrom(other.ClassifierOptions);
      }
      if (other.HasDefaultInputAudioSampleRate) {
        DefaultInputAudioSampleRate = other.DefaultInputAudioSampleRate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseOptions_ == null) {
              BaseOptions = new global::Mediapipe.Tasks.Core.Proto.BaseOptions();
            }
            input.ReadMessage(BaseOptions);
            break;
          }
          case 18: {
            if (classifierOptions_ == null) {
              ClassifierOptions = new global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptions();
            }
            input.ReadMessage(ClassifierOptions);
            break;
          }
          case 25: {
            DefaultInputAudioSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseOptions_ == null) {
              BaseOptions = new global::Mediapipe.Tasks.Core.Proto.BaseOptions();
            }
            input.ReadMessage(BaseOptions);
            break;
          }
          case 18: {
            if (classifierOptions_ == null) {
              ClassifierOptions = new global::Mediapipe.Tasks.Components.Processors.Proto.ClassifierOptions();
            }
            input.ReadMessage(ClassifierOptions);
            break;
          }
          case 25: {
            DefaultInputAudioSampleRate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the AudioClassifierGraphOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions>(451755788, pb::FieldCodec.ForMessage(3614046306, global::Mediapipe.Tasks.Audio.AudioClassifier.Proto.AudioClassifierGraphOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
