// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/calculators/image/warp_affine_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/calculators/image/warp_affine_calculator.proto</summary>
  public static partial class WarpAffineCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/calculators/image/warp_affine_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WarpAffineCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhtZWRpYXBpcGUvY2FsY3VsYXRvcnMvaW1hZ2Uvd2FycF9hZmZpbmVfY2Fs",
            "Y3VsYXRvci5wcm90bxIJbWVkaWFwaXBlGiRtZWRpYXBpcGUvZnJhbWV3b3Jr",
            "L2NhbGN1bGF0b3IucHJvdG8aHm1lZGlhcGlwZS9ncHUvZ3B1X29yaWdpbi5w",
            "cm90byLQAwobV2FycEFmZmluZUNhbGN1bGF0b3JPcHRpb25zEkYKC2JvcmRl",
            "cl9tb2RlGAEgASgOMjEubWVkaWFwaXBlLldhcnBBZmZpbmVDYWxjdWxhdG9y",
            "T3B0aW9ucy5Cb3JkZXJNb2RlEi0KCmdwdV9vcmlnaW4YAiABKA4yGS5tZWRp",
            "YXBpcGUuR3B1T3JpZ2luLk1vZGUSSwoNaW50ZXJwb2xhdGlvbhgDIAEoDjI0",
            "Lm1lZGlhcGlwZS5XYXJwQWZmaW5lQ2FsY3VsYXRvck9wdGlvbnMuSW50ZXJw",
            "b2xhdGlvbiJLCgpCb3JkZXJNb2RlEhYKEkJPUkRFUl9VTlNQRUNJRklFRBAA",
            "Eg8KC0JPUkRFUl9aRVJPEAESFAoQQk9SREVSX1JFUExJQ0FURRACIkkKDUlu",
            "dGVycG9sYXRpb24SFQoRSU5URVJfVU5TUEVDSUZJRUQQABIQCgxJTlRFUl9M",
            "SU5FQVIQARIPCgtJTlRFUl9DVUJJQxACMlUKA2V4dBIcLm1lZGlhcGlwZS5D",
            "YWxjdWxhdG9yT3B0aW9ucxjHu5iyASABKAsyJi5tZWRpYXBpcGUuV2FycEFm",
            "ZmluZUNhbGN1bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, global::Mediapipe.GpuOriginReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.WarpAffineCalculatorOptions), global::Mediapipe.WarpAffineCalculatorOptions.Parser, new[]{ "BorderMode", "GpuOrigin", "Interpolation" }, null, new[]{ typeof(global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode), typeof(global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation) }, new pb::Extension[] { global::Mediapipe.WarpAffineCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WarpAffineCalculatorOptions : pb::IMessage<WarpAffineCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WarpAffineCalculatorOptions> _parser = new pb::MessageParser<WarpAffineCalculatorOptions>(() => new WarpAffineCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WarpAffineCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.WarpAffineCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WarpAffineCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WarpAffineCalculatorOptions(WarpAffineCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      borderMode_ = other.borderMode_;
      gpuOrigin_ = other.gpuOrigin_;
      interpolation_ = other.interpolation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WarpAffineCalculatorOptions Clone() {
      return new WarpAffineCalculatorOptions(this);
    }

    /// <summary>Field number for the "border_mode" field.</summary>
    public const int BorderModeFieldNumber = 1;
    private readonly static global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode BorderModeDefaultValue = global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode.BorderUnspecified;

    private global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode borderMode_;
    /// <summary>
    /// Pixel extrapolation method.
    /// When converting image to tensor it may happen that tensor needs to read
    /// pixels outside image boundaries. Border mode helps to specify how such
    /// pixels will be calculated.
    ///
    /// BORDER_REPLICATE is used by default.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode BorderMode {
      get { if ((_hasBits0 & 1) != 0) { return borderMode_; } else { return BorderModeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        borderMode_ = value;
      }
    }
    /// <summary>Gets whether the "border_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBorderMode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "border_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBorderMode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "gpu_origin" field.</summary>
    public const int GpuOriginFieldNumber = 2;
    private readonly static global::Mediapipe.GpuOrigin.Types.Mode GpuOriginDefaultValue = global::Mediapipe.GpuOrigin.Types.Mode.Default;

    private global::Mediapipe.GpuOrigin.Types.Mode gpuOrigin_;
    /// <summary>
    /// For CONVENTIONAL mode for OpenGL, input image starts at bottom and needs
    /// to be flipped vertically as tensors are expected to start at top.
    /// (DEFAULT or unset interpreted as CONVENTIONAL.)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.GpuOrigin.Types.Mode GpuOrigin {
      get { if ((_hasBits0 & 2) != 0) { return gpuOrigin_; } else { return GpuOriginDefaultValue; } }
      set {
        _hasBits0 |= 2;
        gpuOrigin_ = value;
      }
    }
    /// <summary>Gets whether the "gpu_origin" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGpuOrigin {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "gpu_origin" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGpuOrigin() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "interpolation" field.</summary>
    public const int InterpolationFieldNumber = 3;
    private readonly static global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation InterpolationDefaultValue = global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation.InterUnspecified;

    private global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation interpolation_;
    /// <summary>
    /// Sampling method for neighboring pixels.
    /// INTER_LINEAR (bilinear) linearly interpolates from the nearest 4 neighbors.
    /// INTER_CUBIC (bicubic) interpolates a small neighborhood with cubic weights.
    /// INTER_UNSPECIFIED or unset interpreted as INTER_LINEAR.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation Interpolation {
      get { if ((_hasBits0 & 4) != 0) { return interpolation_; } else { return InterpolationDefaultValue; } }
      set {
        _hasBits0 |= 4;
        interpolation_ = value;
      }
    }
    /// <summary>Gets whether the "interpolation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInterpolation {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "interpolation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInterpolation() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WarpAffineCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WarpAffineCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BorderMode != other.BorderMode) return false;
      if (GpuOrigin != other.GpuOrigin) return false;
      if (Interpolation != other.Interpolation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBorderMode) hash ^= BorderMode.GetHashCode();
      if (HasGpuOrigin) hash ^= GpuOrigin.GetHashCode();
      if (HasInterpolation) hash ^= Interpolation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBorderMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BorderMode);
      }
      if (HasGpuOrigin) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GpuOrigin);
      }
      if (HasInterpolation) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Interpolation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBorderMode) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BorderMode);
      }
      if (HasGpuOrigin) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GpuOrigin);
      }
      if (HasInterpolation) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Interpolation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBorderMode) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BorderMode);
      }
      if (HasGpuOrigin) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GpuOrigin);
      }
      if (HasInterpolation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Interpolation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WarpAffineCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasBorderMode) {
        BorderMode = other.BorderMode;
      }
      if (other.HasGpuOrigin) {
        GpuOrigin = other.GpuOrigin;
      }
      if (other.HasInterpolation) {
        Interpolation = other.Interpolation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BorderMode = (global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode) input.ReadEnum();
            break;
          }
          case 16: {
            GpuOrigin = (global::Mediapipe.GpuOrigin.Types.Mode) input.ReadEnum();
            break;
          }
          case 24: {
            Interpolation = (global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BorderMode = (global::Mediapipe.WarpAffineCalculatorOptions.Types.BorderMode) input.ReadEnum();
            break;
          }
          case 16: {
            GpuOrigin = (global::Mediapipe.GpuOrigin.Types.Mode) input.ReadEnum();
            break;
          }
          case 24: {
            Interpolation = (global::Mediapipe.WarpAffineCalculatorOptions.Types.Interpolation) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the WarpAffineCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Pixel extrapolation methods. See @border_mode.
      /// </summary>
      public enum BorderMode {
        [pbr::OriginalName("BORDER_UNSPECIFIED")] BorderUnspecified = 0,
        [pbr::OriginalName("BORDER_ZERO")] BorderZero = 1,
        [pbr::OriginalName("BORDER_REPLICATE")] BorderReplicate = 2,
      }

      /// <summary>
      /// Pixel sampling interpolation methods. See @interpolation.
      /// </summary>
      public enum Interpolation {
        [pbr::OriginalName("INTER_UNSPECIFIED")] InterUnspecified = 0,
        [pbr::OriginalName("INTER_LINEAR")] InterLinear = 1,
        [pbr::OriginalName("INTER_CUBIC")] InterCubic = 2,
      }

    }
    #endregion

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the WarpAffineCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.WarpAffineCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.WarpAffineCalculatorOptions>(373693895, pb::FieldCodec.ForMessage(2989551162, global::Mediapipe.WarpAffineCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
