name: Bug Report Form
description: File a bug report.
title: '[BUG]: '
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        This is a bug report form.\
        If you are having trouble building libraries or apps, please use build/install form instead.

        * Be sure to check that the bug is still present in the latest commit.
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/homuler/MediaPipeUnityPlugin/issues).
        * If the issue is caused by MediaPipe, you may want to open an issue in google/mediapipe repo instead.

  - type: input
    id: version
    attributes:
      label: Plugin version or commit id
    validations:
      required: true

  - type: input
    id: host_os
    attributes:
      label: Your Host OS
      description: OS where UnityEditor runs
      placeholder: e.g. Ubuntu 20.04, Windows 10 Home, macOS Monterey 12.2
    validations:
      required: true

  - type: dropdown
    id: target_platform
    attributes:
      label: Target Platform
      multiple: true
      options:
        - UnityEditor
        - Windows Standalone
        - Mac Standalone
        - Linux Standalone
        - Android
        - iOS
        - WebGL
    validations:
      required: true

  - type: input
    id: target_device
    attributes:
      label: Target Device
      description: Device name where the bug occurs
      placeholder: e.g. MacBook Pro 14-inch (2021), iPhone 13, Google Pixel 6 Pro

  - type: textarea
    id: windows_build_env
    attributes:
      label: [Windows Only] Visual Studio C++ and Windows SDK version
      description: |
        Required if your host OS is Windows and the Target Platform is UnityEditor or PC Standalone.
      placeholder: |
        Visual Studio C++: 14.16.27023
        Windows SDK: 10.0.10240.0

  - type: textarea
    id: linux_build_env
    attributes:
      label: [Linux Only] GCC/G++ and GLIBC version
      description: |
        Required if your host OS is Linux and the Target Platform is UnityEditor or Linux Standalone.\
        You can get GLIBC version by running `ldd --version`.
      placeholder: |
        GCC: 11.1.0
        G++: 11.1.0
        GLIBC: GNU libc 2.33

  - type: textarea
    id: android_build_env
    attributes:
      label: [Android Only] Android Build Tools and NDK version
      description: Required if the Target Platform is Android
      placeholder: |
        Build Tools: 30.0.2
        NDK: 21.4.7075529

  - type: input
    id: ios_build_env
    attributes:
      label: [iOS Only] XCode version
      description: Required if the Target Platform is iOS

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Describe the bug. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is your expected behaviour?
      description: Describe what you expected to happen and list out what you were doing.
      value: |
        **Expectation**: ....

        **Steps**:

        1. 
        2. 
        3. 

        Add more steps as needed
    validations:
      required: true

  - type: textarea
    attributes:
      label: Full Error Log
      description: |
        If you have a command line error, copy and paste it here.
        If you have a log file, please attach Editor.log (if it occurs on Unity Editor) or Player.log (if it occurs at runtime).
        See https://docs.unity3d.com/Manual/LogFiles.html
      value: |
        <details><summary>Error Log</summary><p>

        ```
          // put code here in between the backticks or attach log file 
        ```
        </p></details>

        **Put images here if applicable**
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible fixes or solutions
      description: List any possible fixes/suggestions that you have in mind that could solve this issue.

  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
