name: Build/Install Issue
description: Report issues that you found while building/installing the plugin.
labels: ["type:build/install"]
body:
  - type: markdown
    attributes:
      value: |
        This is a build/install form.\
        If you are having trouble running apps (includeing the sample app), please [choose bug report form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new/choose) instead.

        * Make sure you're using the latest version.
        * Check [the troubleshooting page](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#troubleshooting) to see if the solution is listed there.
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/homuler/MediaPipeUnityPlugin/issues).

  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version or Commit ID
      placeholder: v0.12.0
    validations:
      required: true

  - type: input
    id: unity_version
    attributes:
      label: Unity Version
      placeholder: 2022.3.6f1
    validations:
      required: true

  - type: input
    id: host_os
    attributes:
      label: Your Host OS
      description: OS where you're building/installing the plugin
      placeholder: Ubuntu 20.04, Windows 10 Home, macOS Monterey 12.2
    validations:
      required: true

  - type: dropdown
    id: target_platform
    attributes:
      label: Target Platform
      multiple: true
      options:
        - UnityEditor
        - Windows Standalone
        - Mac Standalone
        - Linux Standalone
        - Android
        - iOS
        - WebGL
    validations:
      required: true

  - type: textarea
    id: windows_build_env
    attributes:
      label: "[Windows Only] Visual Studio C++ and Windows SDK Version"
      description: |
        Required if your host OS is Windows and the Target Platform is UnityEditor or PC Standalone.
      placeholder: |
        Visual Studio C++: 14.16.27023
        Windows SDK: 10.0.10240.0

  - type: textarea
    id: linux_build_env
    attributes:
      label: "[Linux Only] GCC/G++ and GLIBC Version"
      description: |
        Required if your host OS is Linux and the Target Platform is UnityEditor or Linux Standalone.\
        You can get GLIBC version by running `ldd --version`.
      placeholder: |
        GCC: 11.1.0
        G++: 11.1.0
        GLIBC: GNU libc 2.33

  - type: textarea
    id: android_build_env
    attributes:
      label: "[Android Only] Android Build Tools and NDK Version"
      description: Required if the Target Platform is Android
      placeholder: |
        Build Tools: 30.0.2
        NDK: 21.4.7075529

  - type: input
    id: ios_build_env
    attributes:
      label: "[iOS Only] XCode Version"
      description: Required if the Target Platform is iOS

  - type: textarea
    id: steps
    attributes:
      label: Command Sequences
      description: |
        List the commands and operations you performed, in order and as best you can.\
        Be careful to describe what you actually did (e.g. run `export PYTHON_BIN_PATH=...`), not what you wanted to do (e.g. set `PYTHON_BIN_PATH`).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Log
      description: |
        Attach _full_ log in _text_ format.\
        When executing build command, make sure to add `-vv` option (e.g. `python build.py build --desktop cpu -vv`).

        It is preferable to include a log of commands executed during installation (e.g. `sudo apt-get install ...`).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        If there is something that does not fit in the above form, describe it here.
