name: Feature Request Form
description: Requesting a new feature or changes to an existing feature
title: '[FEATURE REQUEST] feature name'
body:
  - type: textarea
    attributes:
      label: Problem
      description: Tell us about the problem and its negative impacts.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible Solution
      description: If you have an idea, please tell us what might solve the above problem.

  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else we should know about this feature request?
