name: Other Issue
description: Fallback form. Use this for any other issues.
body:
  - type: markdown
    attributes:
      value: |
        This is a fallback form.

        Do not use this form if you are creating an issue about a bug or build.\
        If you create an issue using this form even though there is more appropriate one, we may silently close it.

        * If you don't know how to use MediaPipe itself, please ask it in the official community.
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/homuler/MediaPipeUnityPlugin/issues).

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe your issue.\
        Be careful to include all the context needed to understand it.
    validations:
      required: true
