load("//mediapipe_api/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_android",
    srcs = [
      # "MediaPipeUnityPlayerActivity.java",
    ],
    deps = [
      # "@unity//:activity",
      "//third_party:opencv",
    ],
    jni_deps = [
      "//mediapipe_api:mediapipe_c",
    ],
)
