// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/calculators/util/rect_to_render_scale_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/calculators/util/rect_to_render_scale_calculator.proto</summary>
  public static partial class RectToRenderScaleCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/calculators/util/rect_to_render_scale_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RectToRenderScaleCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkBtZWRpYXBpcGUvY2FsY3VsYXRvcnMvdXRpbC9yZWN0X3RvX3JlbmRlcl9z",
            "Y2FsZV9jYWxjdWxhdG9yLnByb3RvEgltZWRpYXBpcGUaJG1lZGlhcGlwZS9m",
            "cmFtZXdvcmsvY2FsY3VsYXRvci5wcm90byLFAQoiUmVjdFRvUmVuZGVyU2Nh",
            "bGVDYWxjdWxhdG9yT3B0aW9ucxIYCgptdWx0aXBsaWVyGAEgASgCOgQwLjAx",
            "EicKGHByb2Nlc3NfdGltZXN0YW1wX2JvdW5kcxgCIAEoCDoFZmFsc2UyXAoD",
            "ZXh0EhwubWVkaWFwaXBlLkNhbGN1bGF0b3JPcHRpb25zGPHl5Y4BIAEoCzIt",
            "Lm1lZGlhcGlwZS5SZWN0VG9SZW5kZXJTY2FsZUNhbGN1bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.RectToRenderScaleCalculatorOptions), global::Mediapipe.RectToRenderScaleCalculatorOptions.Parser, new[]{ "Multiplier", "ProcessTimestampBounds" }, null, null, new pb::Extension[] { global::Mediapipe.RectToRenderScaleCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RectToRenderScaleCalculatorOptions : pb::IMessage<RectToRenderScaleCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RectToRenderScaleCalculatorOptions> _parser = new pb::MessageParser<RectToRenderScaleCalculatorOptions>(() => new RectToRenderScaleCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RectToRenderScaleCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.RectToRenderScaleCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectToRenderScaleCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectToRenderScaleCalculatorOptions(RectToRenderScaleCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      multiplier_ = other.multiplier_;
      processTimestampBounds_ = other.processTimestampBounds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RectToRenderScaleCalculatorOptions Clone() {
      return new RectToRenderScaleCalculatorOptions(this);
    }

    /// <summary>Field number for the "multiplier" field.</summary>
    public const int MultiplierFieldNumber = 1;
    private readonly static float MultiplierDefaultValue = 0.01F;

    private float multiplier_;
    /// <summary>
    /// Multiplier to apply to the rect size.
    /// If one defined `thickness` for RenderData primitives for object (e.g. pose,
    /// hand or face) of size `A` then multiplier should be `1/A`. It means that
    /// when actual object size on the image will be `B`, than all RenderData
    /// primitives will be scaled with factor `B/A`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Multiplier {
      get { if ((_hasBits0 & 1) != 0) { return multiplier_; } else { return MultiplierDefaultValue; } }
      set {
        _hasBits0 |= 1;
        multiplier_ = value;
      }
    }
    /// <summary>Gets whether the "multiplier" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMultiplier {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "multiplier" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMultiplier() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "process_timestamp_bounds" field.</summary>
    public const int ProcessTimestampBoundsFieldNumber = 2;
    private readonly static bool ProcessTimestampBoundsDefaultValue = false;

    private bool processTimestampBounds_;
    /// <summary>
    /// When true, Process is called for every new timestamp bound, with or without
    /// new packets.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ProcessTimestampBounds {
      get { if ((_hasBits0 & 2) != 0) { return processTimestampBounds_; } else { return ProcessTimestampBoundsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        processTimestampBounds_ = value;
      }
    }
    /// <summary>Gets whether the "process_timestamp_bounds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProcessTimestampBounds {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "process_timestamp_bounds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProcessTimestampBounds() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RectToRenderScaleCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RectToRenderScaleCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Multiplier, other.Multiplier)) return false;
      if (ProcessTimestampBounds != other.ProcessTimestampBounds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMultiplier) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Multiplier);
      if (HasProcessTimestampBounds) hash ^= ProcessTimestampBounds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMultiplier) {
        output.WriteRawTag(13);
        output.WriteFloat(Multiplier);
      }
      if (HasProcessTimestampBounds) {
        output.WriteRawTag(16);
        output.WriteBool(ProcessTimestampBounds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMultiplier) {
        output.WriteRawTag(13);
        output.WriteFloat(Multiplier);
      }
      if (HasProcessTimestampBounds) {
        output.WriteRawTag(16);
        output.WriteBool(ProcessTimestampBounds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMultiplier) {
        size += 1 + 4;
      }
      if (HasProcessTimestampBounds) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RectToRenderScaleCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasMultiplier) {
        Multiplier = other.Multiplier;
      }
      if (other.HasProcessTimestampBounds) {
        ProcessTimestampBounds = other.ProcessTimestampBounds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Multiplier = input.ReadFloat();
            break;
          }
          case 16: {
            ProcessTimestampBounds = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            Multiplier = input.ReadFloat();
            break;
          }
          case 16: {
            ProcessTimestampBounds = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the RectToRenderScaleCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.RectToRenderScaleCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.RectToRenderScaleCalculatorOptions>(299463409, pb::FieldCodec.ForMessage(2395707274, global::Mediapipe.RectToRenderScaleCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
