// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/calculators/util/visibility_copy_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/calculators/util/visibility_copy_calculator.proto</summary>
  public static partial class VisibilityCopyCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/calculators/util/visibility_copy_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VisibilityCopyCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjttZWRpYXBpcGUvY2FsY3VsYXRvcnMvdXRpbC92aXNpYmlsaXR5X2NvcHlf",
            "Y2FsY3VsYXRvci5wcm90bxIJbWVkaWFwaXBlGixtZWRpYXBpcGUvZnJhbWV3",
            "b3JrL2NhbGN1bGF0b3Jfb3B0aW9ucy5wcm90byK4AQofVmlzaWJpbGl0eUNv",
            "cHlDYWxjdWxhdG9yT3B0aW9ucxIdCg9jb3B5X3Zpc2liaWxpdHkYASABKAg6",
            "BHRydWUSGwoNY29weV9wcmVzZW5jZRgCIAEoCDoEdHJ1ZTJZCgNleHQSHC5t",
            "ZWRpYXBpcGUuQ2FsY3VsYXRvck9wdGlvbnMYpZy4rQEgASgLMioubWVkaWFw",
            "aXBlLlZpc2liaWxpdHlDb3B5Q2FsY3VsYXRvck9wdGlvbnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.VisibilityCopyCalculatorOptions), global::Mediapipe.VisibilityCopyCalculatorOptions.Parser, new[]{ "CopyVisibility", "CopyPresence" }, null, null, new pb::Extension[] { global::Mediapipe.VisibilityCopyCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VisibilityCopyCalculatorOptions : pb::IMessage<VisibilityCopyCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VisibilityCopyCalculatorOptions> _parser = new pb::MessageParser<VisibilityCopyCalculatorOptions>(() => new VisibilityCopyCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VisibilityCopyCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.VisibilityCopyCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibilityCopyCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibilityCopyCalculatorOptions(VisibilityCopyCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      copyVisibility_ = other.copyVisibility_;
      copyPresence_ = other.copyPresence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VisibilityCopyCalculatorOptions Clone() {
      return new VisibilityCopyCalculatorOptions(this);
    }

    /// <summary>Field number for the "copy_visibility" field.</summary>
    public const int CopyVisibilityFieldNumber = 1;
    private readonly static bool CopyVisibilityDefaultValue = true;

    private bool copyVisibility_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CopyVisibility {
      get { if ((_hasBits0 & 1) != 0) { return copyVisibility_; } else { return CopyVisibilityDefaultValue; } }
      set {
        _hasBits0 |= 1;
        copyVisibility_ = value;
      }
    }
    /// <summary>Gets whether the "copy_visibility" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCopyVisibility {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "copy_visibility" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCopyVisibility() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "copy_presence" field.</summary>
    public const int CopyPresenceFieldNumber = 2;
    private readonly static bool CopyPresenceDefaultValue = true;

    private bool copyPresence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CopyPresence {
      get { if ((_hasBits0 & 2) != 0) { return copyPresence_; } else { return CopyPresenceDefaultValue; } }
      set {
        _hasBits0 |= 2;
        copyPresence_ = value;
      }
    }
    /// <summary>Gets whether the "copy_presence" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCopyPresence {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "copy_presence" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCopyPresence() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VisibilityCopyCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VisibilityCopyCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CopyVisibility != other.CopyVisibility) return false;
      if (CopyPresence != other.CopyPresence) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCopyVisibility) hash ^= CopyVisibility.GetHashCode();
      if (HasCopyPresence) hash ^= CopyPresence.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCopyVisibility) {
        output.WriteRawTag(8);
        output.WriteBool(CopyVisibility);
      }
      if (HasCopyPresence) {
        output.WriteRawTag(16);
        output.WriteBool(CopyPresence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCopyVisibility) {
        output.WriteRawTag(8);
        output.WriteBool(CopyVisibility);
      }
      if (HasCopyPresence) {
        output.WriteRawTag(16);
        output.WriteBool(CopyPresence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCopyVisibility) {
        size += 1 + 1;
      }
      if (HasCopyPresence) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VisibilityCopyCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasCopyVisibility) {
        CopyVisibility = other.CopyVisibility;
      }
      if (other.HasCopyPresence) {
        CopyPresence = other.CopyPresence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CopyVisibility = input.ReadBool();
            break;
          }
          case 16: {
            CopyPresence = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CopyVisibility = input.ReadBool();
            break;
          }
          case 16: {
            CopyPresence = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the VisibilityCopyCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.VisibilityCopyCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.VisibilityCopyCalculatorOptions>(363728421, pb::FieldCodec.ForMessage(2909827370, global::Mediapipe.VisibilityCopyCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
