package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "rasterization",
    hdrs = ["rasterization.h"],
    deps = [
        "@com_google_mediapipe//mediapipe/framework/formats/annotation:rasterization_cc_proto",
        "//mediapipe_api:common",
    ],
    alwayslink = True,
)
